name: AVisualizer

on: 
  workflow_dispatch: {}
env: 
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: login heroku
        run: heroku container:login
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven and Push
        run: |
            mvn clean package
            cd avisualizer-back/
            heroku plugins:install java
            heroku deploy:jar target/avisualizer-back.jar --app avisualizer
